
services:
  flightbox:
    image: flightbox:0.2.1
    build:
      context: /workspaces/pi_client
      dockerfile: docker/Dockerfile
    container_name: flightbox
    volumes:
      - /ramdrive/ip.addr:/ip_address/ip.addr:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /workspaces/pi_client/.env:/app_env/.env:ro
    cap_drop:
      - all
    security_opt:
      - no-new-privileges
    ipc: private
    restart: always
    networks:
      - flightbox-net
    logging:
      driver: "json-file"
      options:
        max-size: "16m"
networks:
  flightbox-net:
    name: flightbox-net
