
services:
  flightbox_client:
    image: flightbox_client:0.3.0
    build:
      context: $HOME/flightbox.d/
      dockerfile: ./docker/Dockerfile
    container_name: flightbox_client
    volumes:
      - $HOME/flightbox.d/docker/.env:/app_env/.env:ro
      - /ramdrive/ip.addr:/ip_address/ip.addr:ro
    cap_drop:
      - all
    security_opt:
      - no-new-privileges
    ipc: private
    restart: always
    networks:
      - flightbox_client-net
    deploy:
      resources:
        limits:
          memory: 64m
    logging:
      options:
        max-size: 10m
networks:
  flightbox_client-net:
    name: flightbox_client-net
